### ISSUE TITLE
gosocket development

### ISSUE THREAD

**Issue by biggboy021** [golangpros/gosocket#1]
hey team so this is the first framework in this organization

open to contribution:
- @krishpranav 
- @NukeWilliams can contribute to it

**Comment by krishpranav** [comment]
hey @biggboy021 thanks for inviting me to your orgnization for developing go frameworks

**Comment by biggboy021** [comment]
its my pleasure to have you in this organization!

**Comment by krishpranav** [comment]
😄 soon i will work in gosocket!

**Comment by biggboy021** [comment]
thanks

**Comment by NukeWilliams** [comment]
woah intresting framework! socket in golang

**Comment by NukeWilliams** [comment]
will help you @biggboy021
